### ISSUE TITLE
Wider "comments" input field s'il vous plait (please)

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [BlakeBarrett/snse-android#7]
See ^ up there

Or ... I made a "comment" with '#bug' in it to help locate the in-moment idea

**Comment by BlakeBarrett** [comment]
Good call!
This will DEFINITELY be included in the next release!

**Comment by BlakeBarrett** [comment]
Version 1.1.1 was just pushed to Google Play with this fix.
Disfrútalo.
